---
version: '2'
services:
  web:
    build: .
    command: bin/entrypoint.sh
    environment:
      - ACCESS_KEY
      - ACCESS_SECRET
      - VIRTUAL_HOST=mydjangoapp.docker
    ports:
      - 8000
    volumes:
      - .:/code/
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=app
